# Generated by Django 3.0.7 on 2021-02-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210223_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='twiteer_link',
            new_name='twitter_link',
        ),
    ]
